
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: danielatonge/hockey-frontend
        tags: ver2_release
        registry: docker.io
        username: ${{ secrets.LOGIN }}
        password: ${{ secrets.HUB_PASS }}
        
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USER  }}
        key: ${{ secrets.KEY }}
        port: 22
        script_stop: true
        script: |
          cd /opt/temp/front/
          bash deploy_docker.sh
